# Generated by Django 6.0.3 on 2026-03-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rake', models.FloatField(blank=True, null=True)),
                ('stack_depth', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=1024)),
                ('hand', models.CharField(db_index=True, max_length=10)),
                ('actions', models.JSONField()),
                ('ev', models.FloatField(blank=True, null=True)),
                ('equity', models.FloatField(blank=True, null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='solutions.solution')),
            ],
            options={
                'indexes': [models.Index(fields=['solution', 'path', 'hand'], name='solutions_s_solutio_cbf674_idx')],
            },
        ),
    ]
