# Generated by Django 6.0.3 on 2026-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_strategylock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='description',
        ),
        migrations.AddField(
            model_name='solution',
            name='flop_texture',
            field=models.CharField(choices=[('High', 'High Board'), ('Low', 'Low Board'), ('Paired', 'Paired Board'), ('Monotone', 'Monotone Board'), ('Rainbow', 'Rainbow Board'), ('Straight-Friendly', 'Straight-Friendly')], default='Rainbow', max_length=50),
        ),
        migrations.AlterField(
            model_name='solution',
            name='rake',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='stack_depth',
            field=models.IntegerField(default=100),
        ),
    ]
