# Generated by Django 6.0.3 on 2026-03-19 07:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_solverconfig_solution_solver_config'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solution',
            index=django.contrib.postgres.indexes.GinIndex(fields=['config'], name='solution_config_gin'),
        ),
        migrations.AddIndex(
            model_name='solverconfig',
            index=django.contrib.postgres.indexes.GinIndex(fields=['settings'], name='solverconfig_settings_gin'),
        ),
    ]
