# Generated by Django 6.0.3 on 2026-03-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_solution_solution_config_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='ante',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solution',
            name='game_type',
            field=models.CharField(default='6-Max', max_length=50),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['game_type', 'stack_depth', 'ante'], name='solutions_s_game_ty_a34f13_idx'),
        ),
    ]
